blog/urls.py
from django.urls import path
from .views import blog_home_view, blog_post_view, blog_list_view, blog_list_suggests_view

app_name = 'blog_app'
urlpatterns = [
    path('', blog_home_view, name= 'blog_home_url'),
    path('list', blog_list_view, name= 'blog_list_url'),
    path('suggests-list', blog_list_suggests_view, name= 'blog_list_suggests_url'),
    path('<slug>', blog_post_view, name= 'blog_post_url'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# for statics,media files
from django.conf import settings
from django.conf.urls.static import static

app_name = 'url'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls'), name= 'home'),
    path('about/', include('about_page.urls'), name= 'about'),
    path('contact/', include('contact_page.urls'), name= 'contact'),
    path('pricing/', include('pricing_page.urls'), name= 'pricing'),
    path('faq/', include('faq_page.urls'), name= 'faq'),
    path('blog/', include('blog.urls'), name= 'blog'),
    path('portfolio/', include('portfolio.urls'), name= 'portfolio'),
]

if settings.DEBUG:
    # add root 'static' files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add root 'media' files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from .views import portfolio_home_view, portfolio_post_view

app_name = 'portfolio_app'
urlpatterns = [
    path('', portfolio_home_view, name= 'portfolio_home_url'),
    path('<slug>', portfolio_post_view, name= 'portfolio_post_url'),
]

portfolio/models.py
from django.db import models
from extensions.myUtilsForJalali import jalali_convertor

# Create your models here.
class Portfolio(models.Model):
	title = models.CharField(max_length=120)
	slug = models.SlugField(max_length=50, default="")
	description1 = models.TextField()
	image1 = models.ImageField(upload_to='portfolio-image/', null=False, blank=False)
	image2 = models.ImageField(upload_to='portfolio-image/', null=True, blank=True)
	image3 = models.ImageField(upload_to='portfolio-image/', null=True, blank=True)
	description2 = models.TextField(null=True, blank=True)
	# TIMES:
	created_time = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	publish_time = models.DateTimeField(auto_now=True, blank=True, null=True)
	# STATUS FIELD:
	STATUS_LIST = (
			("p", "publish"),
			("d", "draft"),
		)
	status = models.CharField(max_length=1, choices=STATUS_LIST, default="p", )
	suggest = models.BooleanField(default=False)

	# TIME CONVERTOR TO JALALI FORMAT:
	def j_created_time(self):
		return jalali_convertor(self.created_time, lang_format="en", time_status="on")
	j_created_time.short_description = "created_time"
	def j_publish_time(self):
		return jalali_convertor(self.publish_time)
	j_publish_time.short_description = "published_time"

portfolio/views.py
from django.shortcuts import render
from .models import Portfolio


# blog_home view
def portfolio_home_view(request):
	portfolios = Portfolio.objects.all().filter(status = "p")
	context = {
		"page_title": "نمونه کارها",
		"portfolios": portfolios,
	}
	return render(request, 'portfolio/portfolio-home.html', context)


# portfolio_post view
def portfolio_post_view(request, slug):
	try:
		portfolio = Portfolio.objects.all().get(slug=slug)
		templateName = 'portfolio/portfolio-post.html'
	except:
		portfolio = None
		templateName = "portfolio/portfolio-post.html"
	context = {
		"page_title": portfolio.title,
		"portfolio": portfolio,
	}
	return render(request, templateName, context)

templates/portfolio/portfolio-home.html
{% extends 'bases/base-templates.html' %}
{% load static %}

        <!-- Page Content-->
        {% block first_row %}
        <section class="py-5">
            <div class="container px-5 my-5">
                <div class="text-center mb-5">
                    <h1 class="fw-bolder">کار های ما</h1>
                    <p class="lead fw-normal text-muted mb-0">نمونه کار های شرکت</p>
                </div>
                <div class="row gx-5">
                    {% for item in portfolios %}
                    <div class="col-lg-6">
                        <div class="position-relative mb-5">
                            <img class="img-fluid rounded-3 mb-3" src="{{item.image1.url}}"
                                alt="{{item.image1.name}}" />
                            <a class="h3 fw-bolder text-decoration-none link-dark stretched-link" href="{% url 'portfolio_app:portfolio_post_url' item.slug %}">{{item.title}}</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        {% endblock first_row %}

        <!-- Ready to Work Button -->
        {% block second_row %}
        <section class="py-5 bg-light">
            <div class="container px-5 my-5">
                <h2 class="display-4 fw-bolder mb-4">برای همکاری با ما آماده اید؟</h2>
                <a class="btn btn-lg btn-primary" href="#!">تماس بگیرید</a>
            </div>
        </section>
        {% endblock second_row %}

templates/portfolio/portfolio-post.html
{% extends 'bases/base-templates.html' %}
{% load static %}

        <!-- Page Content-->
        {% block first_row %}
        <section class="py-5">
            <div class="container px-5 my-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center mb-5">
                            <h1 class="fw-bolder">{{portfolio.title}}</h1>
                            <p class="lead fw-normal text-muted mb-0">{{portfolio.description1}}</p>
                        </div>
                    </div>
                </div>
                <div class="row gx-5">
                    <div class="col-12"><img class="img-fluid rounded-3 mb-5" src="{{portfolio.image1.url}}" alt="{{portfolio.image1.name}}" />
                    </div>
                    <div class="col-lg-6"><img class="img-fluid rounded-3 mb-5" src="{{portfolio.image2.url}}" alt="{{portfolio.image2.name}}" />
                    </div>
                    <div class="col-lg-6"><img class="img-fluid rounded-3 mb-5" src="{{portfolio.image3.url}}" alt="{{portfolio.image3.name}}" />
                    </div>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center mb-5">
                            <p class="lead fw-normal text-muted">{{portfolio.description2}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock first_row %}