blog/urls.py
from django.urls import path
from .views import blog_home_view, blog_post_view, blog_list_view, blog_list_suggests_view

app_name = 'blog_app'
urlpatterns = [
    path('', blog_home_view, name= 'blog_home_url'),
    path('list', blog_list_view, name= 'blog_list_url'),
    path('suggests-list', blog_list_suggests_view, name= 'blog_list_suggests_url'),
    path('<slug>', blog_post_view, name= 'blog_post_url'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# for statics,media files
from django.conf import settings
from django.conf.urls.static import static

app_name = 'url'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls'), name= 'home'),
    path('about/', include('about_page.urls'), name= 'about'),
    path('contact/', include('contact_page.urls'), name= 'contact'),
    path('pricing/', include('pricing_page.urls'), name= 'pricing'),
    path('faq/', include('faq_page.urls'), name= 'faq'),
    path('blog/', include('blog.urls'), name= 'blog'),
    path('portfolio/', include('portfolio.urls'), name= 'portfolio'),
]

if settings.DEBUG:
    # add root 'static' files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add root 'media' files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog_articel.models import Article


# blog_home view
def blog_home_view(request):
    articeles = Article.objects.all().order_by("-created_time").filter(suggest=True)[:3]
    last_articel = Article.objects.all()
    context = {
        "page_title": "وبلاگ",
        'articeles': articeles,
        'last_articel': last_articel[len(last_articel)-1:],
    }
    return render(request, 'blog/blog-home.html', context)


# blog_post view
def blog_post_view(request, slug):
    try:
        articel = Article.objects.all().get(slug=slug)
        templateName = 'blog/blog-post.html'
    except:
        articel = None
        templateName = "blog/blog-post.html"
    context = {
        "page_title": articel.title,
        "articel": articel,
    }
    return render(request, templateName, context)

# blog_list view
def blog_list_view(request):
    context = {
        "page_title": "لیست مقالات",
    }
    return render(request, 'blog/blog-list.html', context)

# blog_list_suggests view
def blog_list_suggests_view(request):
    context = {
        "page_title": "لیست مقالات ویژه",
    }
    return render(request, 'blog/blog-list-suggests.html', context)

templates/blog/blog-home.html
{% extends 'bases/base-templates.html' %}
{% load static %}

        <!-- Page Content-->
        {% block first_row %}
        <section class="py-5">
            <div class="container px-5">
                <h1 class="fw-bolder fs-5 mb-4">سنجاق شده</h1>
                <div class="card border-0 shadow rounded-3 overflow-hidden">
                    <div class="card-body p-0">
                        <div class="row gx-0">
                            <div class="col-lg-6 col-xl-5 py-lg-5">
                                <div class="p-4 p-md-5">
                                    {% for item in last_articel %}
                                        {% for cat in item.category.all %}
                                            <div class="badge bg-primary bg-gradient rounded-pill mb-2 fw-light">
                                                {{cat}}
                                            </div>
                                        {% endfor %}
                                        <div class="h2 fw-bolder">{{item.title|truncatechars:30}}</div>
                                        <p>
                                        {{item.text|truncatechars:200}}
                                        </p>
                                        <a class="stretched-link text-decoration-none" href="{% url 'blog_app:blog_post_url' item.slug %}">
                                            ادامه مطلب
                                            <i class="bi bi-arrow-left"></i>
                                        </a>
                                    
                                </div>
                            </div>
                            <div class="col-lg-6 col-xl-7">
                                <div class="bg-featured-blog" style="background-image: url({{item.image.url}})"></div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock first_row %}

        <!-- News Content -->
        {% block second_row %}
        <section class="py-5 bg-light">
            <div class="container px-5">
                <div class="row gx-5">
                    <div class="col-xl-8">
                        <h2 class="fw-bolder fs-5 mb-4">آخرین مقالات</h2>
                        <!-- News item-->
                        {% for item in articeles %}
                            <div class="mb-4">
                                <div class="small text-muted">{{item.j_publish_time}}</div>
                                <a class="link-dark" href="{% url 'blog_app:blog_post_url' item.slug %}">
                                    <h3>{{item.text|truncatechars:90}}</h3>
                                </a>
                            </div>
                        {% endfor %}
                        <div class="text-end mb-5 mb-xl-0">
                            <a class="text-decoration-none" href="{% url 'blog_app:blog_list_url' %}">
                                بیشتر
                                <i class="bi bi-arrow-left"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-4">
                        <div class="card border-0 h-100">
                            <div class="card-body p-4">
                                <div class="d-flex h-100 align-items-center justify-content-center">
                                    <div class="text-center">
                                        <div class="h6 fw-bolder">تماس باما</div>
                                        <p class="text-muted mb-4">
                                            با ما در تماس باشید در:
                                            <br />
                                            <a href="#!">press@domain.com</a>
                                        </p>
                                        <div class="h6 fw-bolder">و مارا دنبال کنید</div>
                                        <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-twitter"></i></a>
                                        <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-facebook"></i></a>
                                        <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-linkedin"></i></a>
                                        <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-youtube"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock second_row %}

        <!-- Blog preview section-->
        {% block third_row %}
        <section class="py-5">
            <div class="container px-5">
                <h2 class="fw-bolder fs-5 mb-4">مقاله های ویژه</h2>
                <div class="row gx-5">

                {% for item in articeles %}
                    <div class="col-lg-4 mb-5">
                        <div class="card h-100 shadow border-0">
                            <img class="card-img-top" src="{{ item.image.url }}" alt="..." />
                            <div class="card-body p-4">
                                {% comment %} category {% endcomment %}
                                {% for cat in item.category.all %}
                                    <div class="badge bg-primary bg-gradient rounded-pill mb-2 fw-light">
                                        {{cat}}
                                    </div>
                                {% endfor %}
                                <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog_app:blog_post_url' item.slug %}">
                                    <div class="h5 card-title mb-3 _text_justify">{{ item.title }}</div>
                                </a>
                                <div class="card-text mb-0 _text_justify">
                                    {{ item.text|truncatechars:200}}
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                <div class="d-flex align-items-end justify-content-between">
                                    <div class="d-flex align-items-center">
                                        <img class="rounded-circle me-3" src="{% static 'img/352-40x40.jpg' %}" alt="..." />
                                        <div class="small">
                                            <div class="fw-bold">حض بیگ</div>
                                            <div class="text-muted">{{item.j_publish_time}} &middot; <span style="font-family: system-ui;">{{item.time_for_read}}</span> دقیقه برای مطالعه</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}  

                </div>
                <div class="text-end mb-5 mb-xl-0">
                    <a class="text-decoration-none" href="{% url 'blog_app:blog_list_suggests_url' %}">
                        مقالات بیشتر
                        <i class="bi bi-arrow-left"></i>
                    </a>
                </div>
            </div>
        </section>
        {% endblock third_row %}

templates/blog/blog-list-suggests.html
{% extends 'bases/base-templates.html' %}
{% load static %}
{% load suggest_articeles_library %}

    <!-- Suggest Content -->
    {% block first_row %}
        {% suggest_articeles_tag %}
    {% endblock first_row %}

templates/blog/blog-list.html
{% extends 'bases/base-templates.html' %}
{% load static %}
{% load last_articeles_library %}

        <!-- last Content -->
        {% block first_row %}
            {% last_articeles_tag %}
        {% endblock first_row %}
        

templates/blog/blog-post.html
{% extends 'bases/base-templates.html' %}
{% load static %}

        <!-- Page Content-->
        {% block first_row %}
        <section class="py-5">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <!--writer informations-->
                    <div class="col-lg-3">
                        <div class="d-flex align-items-center mt-lg-5 mb-4">
                            <img class="img-fluid rounded-circle" src="{% static 'img/1009-50x50.jpg' %}" alt="..." />
                            <div class="ms-3">
                                <div class="fw-bold">حض بیگ</div>
                                <div class="text-muted">اخبار, کسب و کار</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <!-- Post content-->
                        <article>
                            <!-- Post header-->
                            <header class="mb-4">
                                <!-- Post title-->
                                <h1 class="fw-bolder mb-1">{{articel.title}}</h1>
                                <!-- Post meta content-->
                                <div class="text-muted fst-italic mb-2">{{articel.j_publish_time}}</div>
                                <!-- Post categories-->
                                {% for cat in articel.category.all %}
                                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{cat}}</a>
                                {% endfor %}
                            </header>
                            <!-- Preview image figure-->
                            <figure class="mb-4"><img class="img-fluid rounded" src="{{articel.image.url}}" alt="{{articel.image.name}}" />
                            </figure>
                            <!-- Post content-->
                            <section class="mb-5"> {{articel.text|linebreaks}} </section>
                        </article>
                        <!-- Comments section-->
                        <section>
                            <div class="card bg-light">
                                <div class="card-body">
                                    <!-- Comment form-->
                                    <form class="mb-4"><textarea class="form-control" rows="3"
                                            placeholder="یه پیام بزار تا به گفتگو وارد بشی!"></textarea></form>
                                    <!-- Comment with nested comments-->
                                    <div class="d-flex mb-4">
                                        <!-- Parent comment-->
                                        <div class="flex-shrink-0"><img class="rounded-circle" src="{% static 'img/1009-50x50.jpg' %}"
                                                alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">کاربری خندان</div>
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از
                                            طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که
                                            لازم است؟
                                            <!-- Child comment 1-->
                                            <div class="d-flex mt-4">
                                                <div class="flex-shrink-0"><img class="rounded-circle"
                                                        src="{% static 'img/257-50x50.jpg' %}" alt="..." /></div>
                                                <div class="ms-3">
                                                    <div class="fw-bold">ادمین سایت</div>
                                                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
                                                    استفاده از طراحان گرافیک است.
                                                </div>
                                            </div>
                                            <!-- Child comment 2-->
                                            <div class="d-flex mt-4">
                                                <div class="flex-shrink-0"><img class="rounded-circle"
                                                        src="{% static 'img/367-50x50.jpg' %}" alt="..." /></div>
                                                <div class="ms-3">
                                                    <div class="fw-bold">حض بیگ</div>
                                                    آفرین ادمین، جواب درستی دادی به کاربر خندان:)
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Single comment-->
                                    <div class="d-flex">
                                        <div class="flex-shrink-0"><img class="rounded-circle" src="{% static 'img/1009-50x50.jpg' %}"
                                                alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">کاربر خندان</div>
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </section>
        {% endblock first_row %}