about_page/urls.py
from django.urls import path
from .views import about_view

app_name = 'about_app'
urlpatterns = [
    path('', about_view, name= 'about_url'),
]

blog/urls.py
from django.urls import path
from .views import blog_home_view, blog_post_view, blog_list_view, blog_list_suggests_view

app_name = 'blog_app'
urlpatterns = [
    path('', blog_home_view, name= 'blog_home_url'),
    path('list', blog_list_view, name= 'blog_list_url'),
    path('suggests-list', blog_list_suggests_view, name= 'blog_list_suggests_url'),
    path('<slug>', blog_post_view, name= 'blog_post_url'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# for statics,media files
from django.conf import settings
from django.conf.urls.static import static

app_name = 'url'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_page.urls'), name= 'home'),
    path('about/', include('about_page.urls'), name= 'about'),
    path('contact/', include('contact_page.urls'), name= 'contact'),
    path('pricing/', include('pricing_page.urls'), name= 'pricing'),
    path('faq/', include('faq_page.urls'), name= 'faq'),
    path('blog/', include('blog.urls'), name= 'blog'),
    path('portfolio/', include('portfolio.urls'), name= 'portfolio'),
]

if settings.DEBUG:
    # add root 'static' files
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add root 'media' files
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq_page/urls.py
from django.urls import path
from .views import faq_view

app_name = 'faq_app'
urlpatterns = [
    path('', faq_view, name= 'faq_url'),
]

home_page/urls.py
from django.urls import path
from .views import home_view

app_name = 'home_app'
urlpatterns = [
    path('', home_view, name= 'home_url'),
]

portfolio/urls.py
from django.urls import path
from .views import portfolio_home_view, portfolio_post_view

app_name = 'portfolio_app'
urlpatterns = [
    path('', portfolio_home_view, name= 'portfolio_home_url'),
    path('<slug>', portfolio_post_view, name= 'portfolio_post_url'),
]

templates/bases/base-templates.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>قالب شرکتی مدرن | {{ page_title }}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Custom css styles -->
    <link href="{% static 'css/styles-mine.css' %}" rel="stylesheet" />
</head>

<body class="d-flex flex-column h-100">

    <main class="flex-shrink-0">
        
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home_app:home_url' %}">صنایع آلومینیوم</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home_app:home_url' %}">خانه</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about_app:about_url' %}">درباره ما</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact_app:contact_url' %}">تماس با ما</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'pricing_app:pricing_url' %}">پلن ها</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'faq_app:faq_url' %}">سوالات متداول</a></li>
                        <li class="nav-item dropdown">
                            <!--
                                disable dropdown for blog.
                                ********active when create categories. [for developer]*********
                            -->
                            <a class="nav-link text-white" href="{% url 'blog_app:blog_home_url' %}">بلاگ</a>
                            {% comment %} <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="{% url 'blog_app:blog_home_url' %}" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">بلاگ</a> {% endcomment %}
                            {% comment %} <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                <li><a class="dropdown-item" href="{% url 'blog_app:blog_home_url' %}">لیست مقالات</a></li>
                                <li><a class="dropdown-item" href="{% url 'blog_app:blog_post_url' "slug" %}">مقاله</a></li>
                            </ul> {% endcomment %}
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-white" href="{% url 'portfolio_app:portfolio_home_url' %}">نمونه کارها</a>
                            {% comment %} <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="{% url 'portfolio_app:portfolio_home_url' %}" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">نمونه کارها</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                <li><a class="dropdown-item" href="{% url 'portfolio_app:portfolio_home_url' %}">لیست نمونه کارها</a></li>
                                <li><a class="dropdown-item" href="">نمومه کار</a></li>
                            </ul> {% endcomment %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block first_row %}
        <!-- 
            using by:
            * home.html
            * 
         -->
        {% endblock first_row %}

        {% block second_row %}
        <!-- 
            using by:
            * home.html
            * 
         -->
        {% endblock second_row %}

        {% block third_row %}
        <!-- 
            using by:
            * home.html
            * 
         -->
        {% endblock third_row %}

        {% block fourth_row %}
        <!-- 
            using by:
            * home.html
            * 
         -->
        {% endblock fourth_row %}
    </main>

    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto" style="font-family: system-ui;">
                    <div class="small m-0 text-white">Copyright &copy; <a href="https://hozbig.ir"
                            class="link-light">HOZBIG.ir</a> 2021</div>
                </div>
                <div class="col-auto">
                    <a class="link-light small" href="#!">حریم خصوصی</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">شرایط</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">تماس با ما</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>